spring:
  application:
    name: GesundKlinik

  datasource:
    url: jdbc:mysql://localhost:3306/gesundklinik
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate  # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/
  logging:
    level:
      org.springframework.security: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET}


#http://localhost:8080/swagger-ui/index:html#/