spring:
  application:
    name: GesundKlinik

  datasource:
    url: jdbc:mysql://localhost:3306/gesundklinik
    username: root
    password: 96070643
    driver-class-name: com.mysql.cj.jdbc.Driver

#  security:
#    user:
#      name: adm
#      password: 123

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update  # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/

  logging:
    level:
      org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET:OAJIOh7h5HWSUIBAUIHApuhH}