spring:
  application:
    name: GesundKlinik

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      git commit
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  flyway:
          enabled: false

  logging:
    level:
      org.springframework.security: WARN
      org.hibernate.SQL: OFF

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  security:
    token:
      secret: ${JWT_SECRET}

server:
  port: 8080